version: '2'

services:
  organizr:
    image: organizrtools/organizr-v2
    ports:
      # The HTTP port
      - "${HTTP_PORT}:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      # So that Traefik can listen to the Docker events
      - ${CONFIG_VOLUME}:/config
    labels:
      - traefik.provider=rancher
      - traefik.http.routers.organizr.rule=Host(${ORGANIZR_HOST})
      - traefik.http.routers.organizr.tls=true
      - traefik.http.routers.organizr.tls.certresolver=letsencrypt
