version: '2'

services:
  organizr:
    image: organizrtools/organizr-v2
    ports:
      # The HTTP port
      - "${HTTP_PORT}:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      # So that Traefik can listen to the Docker events
      - ${CONFIG_VOLUME}:/config
