version: '2'

services:
  plex:
    image: linuxserver/plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=${PLEX_VERSION}
      - UMASK_SET=022 #optional
      - PLEX_CLAIM=${PLEX_CLAIM} #optional
    ports:
      - 32400:32400
    volumes:
      - ${CONFIG_VOLUME}:/config
      - ${MEDIA_VOLUME}:/media
    labels:
      - traefik.provider=rancher
      - traefik.http.routers.plex.rule=Host(${PLEX_HOST})
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.tls.certresolver=letsencrypt
